CONTAINER Nfilter                       {
    NAME Nfilter;

    INCLUDE Nbase;

    GROUP NB_GROUP_NODEPROPERTIES       {
        DEFAULT 1;

        REAL NFLT_REAL_HUE              {CUSTOMGUI REALSLIDER; UNIT DEGREE; MIN 0; MAX 360; MINSLIDER 0; MAXSLIDER 360;}
        REAL NFLT_REAL_SATURATION       {CUSTOMGUI REALSLIDER; UNIT PERCENT; MIN -100; MAX 100; MINSLIDER -100; MAXSLIDER 100;}
        REAL NFLT_REAL_LIGHTNESS        {CUSTOMGUI REALSLIDER; UNIT PERCENT; MIN -100; MAX 100; MINSLIDER -100; MAXSLIDER 100; CUSTOMGUI REALSLIDER;}
        BOOL NFLT_BOOL_COLORIZE         {}
        REAL NFLT_REAL_BRIGHNESS        {UNIT PERCENT; MIN -100; MAX 100; CUSTOMGUI REALSLIDER;}
        REAL NFLT_REAL_CONTRAST         {UNIT PERCENT; MIN -100; MAX 100; CUSTOMGUI REALSLIDER;}
        REAL NFLT_REAL_GAMMA            {MIN .1; MAX 100; MAXSLIDER 10; STEP 0.01; CUSTOMGUI REALSLIDER;}
        BOOL NFLT_BOOL_CLIPPING         {}
        REAL NFLT_REAL_LOW_CLIP         {UNIT PERCENT; MIN 0; MAX 10000; MINSLIDER 0; MAXSLIDER 100; CUSTOMGUI REALSLIDER;}
        REAL NFLT_REAL_HIGH_CLIP        {UNIT PERCENT; MIN 0; MAX 10000; MINSLIDER 0; MAXSLIDER 100; CUSTOMGUI REALSLIDER;}
    }

    SHOW NB_GROUP_MASKPROPERTIES;
}
