#ifndef _Nmatrix_H_
#define _Nmatrix_H_

enum {
    NMTX_FIRST                  = 1000,

    NMTX_REAL_DISTANCE,
    NMTX_BOOL_NORMALIZE,
    NMTX_REAL_ADD,

    NMTX_GROUP_MATRIX_5X5       = 1100,

    NMTX_LONG_MATRIX_01,
    NMTX_LONG_MATRIX_02,
    NMTX_LONG_MATRIX_03,
    NMTX_LONG_MATRIX_04,
    NMTX_LONG_MATRIX_05,

    NMTX_LONG_MATRIX_06,
    NMTX_LONG_MATRIX_07,
    NMTX_LONG_MATRIX_08,
    NMTX_LONG_MATRIX_09,
    NMTX_LONG_MATRIX_10,

    NMTX_LONG_MATRIX_11,
    NMTX_LONG_MATRIX_12,
    NMTX_LONG_MATRIX_13,
    NMTX_LONG_MATRIX_14,
    NMTX_LONG_MATRIX_15,

    NMTX_LONG_MATRIX_16,
    NMTX_LONG_MATRIX_17,
    NMTX_LONG_MATRIX_18,
    NMTX_LONG_MATRIX_19,
    NMTX_LONG_MATRIX_20,

    NMTX_LONG_MATRIX_21,
    NMTX_LONG_MATRIX_22,
    NMTX_LONG_MATRIX_23,
    NMTX_LONG_MATRIX_24,
    NMTX_LONG_MATRIX_25,

    NMTX_DUMMY
};

#endif
