#ifndef _Nvrayadvanced_H_
#define _Nvrayadvanced_H_

enum {
    ID_VRAYBRDF_MATERIAL = 1020295,

    NVRAYADVANCED_LINK_MATERIAL = 1000,

    // Groups
    ID_VRAYMATERIALGROUP_COLOR = 850,
    ID_VRAYMATERIALGROUP_LUMINANCE,
    ID_VRAYMATERIALGROUP_TRANSPARENCY,
    ID_VRAYMATERIALGROUP_REFLECTION,
    ID_VRAYMATERIALGROUP_BUMP,
    ID_VRAYMATERIALGROUP_SPECULAR1,
    ID_VRAYMATERIALGROUP_SPECULAR2,
    ID_VRAYMATERIALGROUP_SPECULAR3,
    ID_VRAYMATERIALGROUP_TRANSP,
    ID_VRAYMATERIALGROUP_SUBPOLY,
    ID_VRAYMATERIALGROUP_SPECULAR4,
    ID_VRAYMATERIALGROUP_SPECULAR5,
    ID_VRAYMATERIALGROUP_COLOR2,
    ID_VRAYMATERIALGROUP_MATTE,
    ID_VRAYMATERIALGROUP_SSS,
    ID_VRAYMATERIALGROUP_FLAKES,

    // Use Bool Parameters
    VRAYMATERIAL_USE_COLOR1= 2000,
    VRAYMATERIAL_USE_LUMINANCE,
    VRAYMATERIAL_USE_TRANSPARENCY,
    VRAYMATERIAL_USE_REFLECTION,
    VRAYMATERIAL_USE_BUMP,
    VRAYMATERIAL_USE_SPECULAR1,
    VRAYMATERIAL_USE_SPECULAR2,
    VRAYMATERIAL_USE_SPECULAR3,
    VRAYMATERIAL_USE_VOLUME,
    VRAYMATERIAL_USE_TRANSP,
    VRAYMATERIAL_USE_SPECULAR4,
    VRAYMATERIAL_USE_SPECULAR5,
    VRAYMATERIAL_USE_COLOR2,
    VRAYMATERIAL_USE_MATTE,
    VRAYMATERIAL_USE_SSS,
    VRAYMATERIAL_USE_FLAKES,

    // Shaders
    VRAYMATERIAL_COLOR1_SHADER = 4100,
    VRAYMATERIAL_COLOR1_TRANSPSHADER,
    VRAYMATERIAL_LUMINANCE_SHADER,
    VRAYMATERIAL_LUMINANCE_TRANSPSHADER,
    VRAYMATERIAL_TRANSPARENCY_SHADER,
    VRAYMATERIAL_TRANSPARENCY_TRANSPSHADER,
    VRAYMATERIAL_TRANSPARENCY_GLOSSINESSSHADER,
    VRAYMATERIAL_REFLECTION_SHADER,
    VRAYMATERIAL_REFLECTION_TRANSPSHADER,
    VRAYMATERIAL_BUMP_SHADER,

    VRAYMATERIAL_SPECULAR1_SHADER,
    VRAYMATERIAL_SPECULAR1_TRANSPSHADER,
    VRAYMATERIAL_SPECULAR1_HIGHLIGHTGLOSSSHADER,
    VRAYMATERIAL_SPECULAR1_REFLECTIONGLOSSSHADER,

    VRAYMATERIAL_SPECULAR2_SHADER,
    VRAYMATERIAL_SPECULAR2_TRANSPSHADER,
    VRAYMATERIAL_SPECULAR2_HIGHLIGHTGLOSSSHADER,
    VRAYMATERIAL_SPECULAR2_REFLECTIONGLOSSSHADER,

    VRAYMATERIAL_SPECULAR3_SHADER,
    VRAYMATERIAL_SPECULAR3_TRANSPSHADER,
    VRAYMATERIAL_SPECULAR3_HIGHLIGHTGLOSSSHADER,
    VRAYMATERIAL_SPECULAR3_REFLECTIONGLOSSSHADER,

    VRAYMATERIAL_TRANSP_SHADER,

    VRAYMATERIAL_SPECULAR4_SHADER,
    VRAYMATERIAL_SPECULAR4_TRANSPSHADER,
    VRAYMATERIAL_SPECULAR4_HIGHLIGHTGLOSSSHADER,
    VRAYMATERIAL_SPECULAR4_REFLECTIONGLOSSSHADER,

    VRAYMATERIAL_SPECULAR5_SHADER,
    VRAYMATERIAL_SPECULAR5_TRANSPSHADER,
    VRAYMATERIAL_SPECULAR5_HIGHLIGHTGLOSSSHADER,
    VRAYMATERIAL_SPECULAR5_REFLECTIONGLOSSSHADER,

    VRAYMATERIAL_COLOR2_SHADER,
    VRAYMATERIAL_COLOR2_TRANSPSHADER,

    VRAYMATERIAL_SPECULAR1_ANISOTROPYSHADER,
    VRAYMATERIAL_SPECULAR1_ANISOTROPYROTSHADER,
    VRAYMATERIAL_SPECULAR2_ANISOTROPYSHADER,
    VRAYMATERIAL_SPECULAR2_ANISOTROPYROTSHADER,
    VRAYMATERIAL_SPECULAR3_ANISOTROPYSHADER,
    VRAYMATERIAL_SPECULAR3_ANISOTROPYROTSHADER,
    VRAYMATERIAL_SPECULAR4_ANISOTROPYSHADER,
    VRAYMATERIAL_SPECULAR4_ANISOTROPYROTSHADER,
    VRAYMATERIAL_SPECULAR5_ANISOTROPYSHADER,
    VRAYMATERIAL_SPECULAR5_ANISOTROPYROTSHADER,

    VRAYMATERIAL_MATTE_OPSHADER,
    VRAYMATERIAL_MATTE_ALPHASHADER,

    VRAYMATERIAL_COLOR1_ROUGHNESSTEX,
    VRAYMATERIAL_COLOR2_ROUGHNESSTEX,

    VRAYMATERIAL_SPECULAR1_FRESNELREFLSHADER,
    VRAYMATERIAL_SPECULAR1_FRESNELREFRSHADER,
    VRAYMATERIAL_SPECULAR2_FRESNELREFLSHADER,
    VRAYMATERIAL_SPECULAR2_FRESNELREFRSHADER,
    VRAYMATERIAL_SPECULAR3_FRESNELREFLSHADER,
    VRAYMATERIAL_SPECULAR3_FRESNELREFRSHADER,
    VRAYMATERIAL_SPECULAR4_FRESNELREFLSHADER,
    VRAYMATERIAL_SPECULAR4_FRESNELREFRSHADER,
    VRAYMATERIAL_SPECULAR5_FRESNELREFLSHADER,
    VRAYMATERIAL_SPECULAR5_FRESNELREFRSHADER,

    VRAYMATERIAL_SSS_OVERALLCOLORSHADER,
    VRAYMATERIAL_SSS_SSSCOLORSHADER,
    VRAYMATERIAL_SSS_SCATTERSHADER,
    VRAYMATERIAL_SSS_SCATTERMULTSHADER,

    VRAYMATERIAL_COLOR1_DIRTRADIUSTEX,
    VRAYMATERIAL_COLOR1_DIRTOCCLUDED,
    VRAYMATERIAL_COLOR1_DIRTUNOCCLUDED,

    VRAYMATERIAL_COLOR2_DIRTRADIUSTEX,
    VRAYMATERIAL_COLOR2_DIRTOCCLUDED,
    VRAYMATERIAL_COLOR2_DIRTUNOCCLUDED,

    VRAYMATERIAL_LUMINANCE_DIRTRADIUSTEX,
    VRAYMATERIAL_LUMINANCE_DIRTOCCLUDED,
    VRAYMATERIAL_LUMINANCE_DIRTUNOCCLUDED,

    VRAYMATERIAL_COLOR1_SSSBACKSHADER,

    VRAYMATERIAL_FLAKES_COLORSHADER,
    VRAYMATERIAL_FLAKES_GLOSSINESSSHADER,
    VRAYMATERIAL_FLAKES_ORIENTATIONSHADER,

    _VRAYMATERIAL_DUMMY
};

#endif
