#ifndef _Prefs_cmnodes_H_
#define _Prefs_cmnodes_H_

enum                                    {
    PREF_CMN_MAIN_GROUP                 = 1000,
    PREF_CMN_GROUP_EDITOR,
    PREF_CMN_GROUP_DISPLAY,

    PREF_CMN_FIRST_CONTROL              = 1100,

    PREF_CMN_L_INSERT_NODE,
    PREF_CMN_B_SNAPPING,
    PREF_CMN_L_SNAP_THRESHOLD,
    PREF_CMN_L_GRID_WIDTH,
    PREF_CMN_L_GRID_HEIGHT,
    PREF_CMN_L_PASTE_NODE,
    PREF_CMN_L_NODE_WIDTH,
    PREF_CMN_L_PORT_PADDING,
    PREF_CMN_L_MID_DRAG_THRESHOLD,
    PREF_CMN_B_EMPTYCLIPBOARD__REMOVED,
    PREF_CMN_C_WIRECOLOR,
    PREF_CMN_C_WIREACTIVE,
    PREF_CMN_L_WIRESTYLE,
    PREF_CMN_B_NEWMATERIAL,
    PREF_CMN_B_TOLERANTSELECTION,
    PREF_CMN_B_MID_DRAG_VISIBLE,
    PREF_CMN_B_AUTOLABELS,
    PREF_CMN_C_NOTE_INDICATOR,
    PREF_CMN_L_STAMPSIZE,

    PREF_CMN_GROUP_NODECOLORS           = 1200,
    PREF_CMN_C_NODES_INPUT,
    PREF_CMN_C_NODES_ADJUST,
    PREF_CMN_C_NODES_CHANNELS,
    PREF_CMN_C_NODES_EFFECTS2D,
    PREF_CMN_C_NODES_OUTPUT,
    PREF_CMN_C_NODES_UTILITY,

    CMN_INSERT_ORIGIN                   = 0,
    CMN_INSERT_VIEWCENTER               = 1,
    CMN_INSERT_POSITION                 = 2,
    CMN_INSERT_CURSORPOS                = 3,

    CMN_WIRESTYLE_STRAIGHT              = 0,
    CMN_WIRESTYLE_BEZIER                = 1,

    CMN_STAMPSIZE_SMALL                 = 0,
    CMN_STAMPSIZE_MEDIUM                = 1,
    CMN_STAMPSIZE_LARGE                 = 2,

    PREF_CMN_DUMMY
};

#endif
