CONTAINER RF_MELTMATERIAL
{
	NAME RFMeltMaterial;
	INCLUDE Mpreview;
	INCLUDE Mbase;

	GROUP RF_MELTMATERIAL_SETUP
	{
		DEFAULT 1;
		
        REAL RF_MELTMATERIAL_INDEX {STEP 0.1;}
//        LINK RF_MELTMATERIAL_MAT1 {ACCEPT {Mbase;}}
//        LINK RF_MELTMATERIAL_MAT2 {ACCEPT {Mbase;}}
//        LINK RF_MELTMATERIAL_MAT3 {ACCEPT {Mbase;}}
//        LINK RF_MELTMATERIAL_MAT4 {ACCEPT {Mbase;}}
//        LINK RF_MELTMATERIAL_MAT5 {ACCEPT {Mbase;}}
//        LINK RF_MELTMATERIAL_MAT6 {ACCEPT {Mbase;}}
//        LINK RF_MELTMATERIAL_MAT7 {ACCEPT {Mbase;}}
//        LINK RF_MELTMATERIAL_MAT8 {ACCEPT {Mbase;}}
//        LINK RF_MELTMATERIAL_MAT9 {ACCEPT {Mbase;}}
//        LINK RF_MELTMATERIAL_MAT10 {ACCEPT {Mbase;}}
	}
}
