#ifndef _RF_MeltMaterial_H_
#define _RF_MeltMaterial_H_

enum
{
    // setup
    RF_MELTMATERIAL_SETUP		= 1000,
    RF_MELTMATERIAL_INDEX,
    RF_MELTMATERIAL_MAT1,
    RF_MELTMATERIAL_MAT2,
    RF_MELTMATERIAL_MAT3,
    RF_MELTMATERIAL_MAT4,
    RF_MELTMATERIAL_MAT5,
    RF_MELTMATERIAL_MAT6,
    RF_MELTMATERIAL_MAT7,
    RF_MELTMATERIAL_MAT8,
    RF_MELTMATERIAL_MAT9,
    RF_MELTMATERIAL_MAT10,

    RF_MELTMATERIAL_ERROR_CHECK = 100000,
};

#endif
