#ifndef _RF_Mesh_Importer_H_
#define _RF_Mesh_Importer_H_

enum
{
	// combos
	//
	// cache
	M_IMP_CURRENT_FRAME			= 0,
	M_IMP_CORE_FRAME			= 1,
	M_IMP_ALL_FRAME				= 2,
	// attributes
	M_IMP_KEEP					= 0,
	M_IMP_ADD					= 1,
	M_IMP_NO					= 2,

	// groups
	M_IMP_SETUP					= 5000,
	M_IMP_GRP_BIN_CHANNELS,

	// setup
	M_IMP_FILE_PATH,
	M_IMP_NAME,
	M_IMP_PADDING,
	M_IMP_CACHE_MODE,
	M_IMP_CACHE_CORE,
	M_IMP_START_FRAME,
	M_IMP_END_FRAME,
	M_IMP_OFFSET,
	M_IMP_BLUR,
	M_IMP_SCALE,
	M_IMP_LOCK_CURRENT,
	M_IMP_INVERT_SEQUENCE,

	// channels
   // DEPRECATED old parameters (<2.4.3)
	M_IMP_VELOCITY,
	M_IMP_VELOCITY_V,
	M_IMP_TEXTURE,
	M_IMP_TEXTURE_V,

	M_IMP_USERDATA,

	// v2.1
	M_IMP_LOD,
	// MD attributes
	M_IMP_GRP_MD_CHANNELS		= 6000,
	M_IMP_MDVELOCITY,
	M_IMP_MDFORCE,
	M_IMP_MDNORMAL,
	M_IMP_MDNEIGHBORS,
	M_IMP_MDTEXTURE,
	M_IMP_MDAGE,
	M_IMP_MDISOLATION,
	M_IMP_MDVISCOSITY,
	M_IMP_MDDENSITY,
	M_IMP_MDPRESSURE,
	M_IMP_MDMASS,
	M_IMP_MDTEMPERATURE,
	M_IMP_MDVORTICITY,
	M_IMP_MDCURVATURE,
	M_IMP_MDIDENTITY,

	M_IMP_MDVEL_LEN					= 6100,
	M_IMP_MDVEL_SCALE,
	M_IMP_MDFORCE_LEN,
	M_IMP_MDFORCE_SCALE,
	M_IMP_MDNORM_LEN,
	M_IMP_MDNORM_SCALE,
	M_IMP_MDNEIGH_SCALE,
	M_IMP_MDTEX_LEN,
	M_IMP_MDTEX_SCALE,
	M_IMP_MDAGE_SCALE,
	M_IMP_MDISO_SCALE,
	M_IMP_MDVISC_SCALE,
	M_IMP_MDDENS_SCALE,
	M_IMP_MDPRESS_SCALE,
	M_IMP_MDMASS_SCALE,
	M_IMP_MDTEMP_SCALE,
	M_IMP_MDVORT_LEN,
	M_IMP_MDVORT_SCALE,
	M_IMP_MDCURV_SCALE,
	M_IMP_MDID_SCALE,

	M_IMP_FILE_TYPE					= 7000,
	M_IMP_MESH,

	// v2.1.3 render info
        M_IMP_RENDERING					= 8000,
        M_IMP_RENDER_FRAME,
        M_IMP_MB_ITERATION,
	// v2.1.4 Maxwell - RF integration
	M_IMP_CURRENT_PATH,
	// v2.1.5 pivot
	M_IMP_GRP_PIVOT,
	M_IMP_PREV_PIVOT,
	M_IMP_PIVOT,
	// v2.2.4
	M_IMP_BINVEL_LEN,

   // v2.4.3
	M_IMP_CHAN_VELOCITY,
	M_IMP_CHAN_VELOCITY_SCALE,
	M_IMP_CHAN_VELOCITY_MAG,
	M_IMP_CHAN_TEXTURE,
	M_IMP_CHAN_WEIGHT,
   M_IMP_SHARE_ASSETS,
};

#endif
