#ifndef _RF_Particle_Importer_H_
#define _RF_Particle_Importer_H_

enum
{
	// combos
	//
	// cache
	P_IMP_CURRENT_FRAME			= 0,
	P_IMP_CORE_FRAME			= 1,
	P_IMP_ALL_FRAME				= 2,
	// attributes
	P_IMP_KEEP					= 0,
	P_IMP_ADD					= 1,
	P_IMP_NO					= 2,
	// display mode
	P_IMP_TPDEFAULT				= 0,
	P_IMP_PARTICLES				= 1,
	P_IMP_CIRCLES				= 2,
	P_IMP_BOX					= 3,
	// color mode
	P_IMP_COLOR_NONE			= 0,
	P_IMP_COLOR_VELOCITY,
	P_IMP_COLOR_NORMAL,
	P_IMP_COLOR_FORCE,
	P_IMP_COLOR_TEXTUREU,
	P_IMP_COLOR_TEXTUREV,
	P_IMP_COLOR_NEIGHBOR,
	P_IMP_COLOR_AGE,
	P_IMP_COLOR_ISOLATION,
	P_IMP_COLOR_VISCOSITY,
	P_IMP_COLOR_DENSITY,
	P_IMP_COLOR_PRESSURE,
	P_IMP_COLOR_MASS,
	P_IMP_COLOR_TEMPERATURE,
	P_IMP_COLOR_VORTICITY,
	// circles dir
	P_IMP_CAMERA				= 0,
	P_IMP_XY					= 1,
	P_IMP_YZ					= 2,
	P_IMP_XZ					= 3,

	P_IMP_RENDER_TYPE_POINT = 0,
	P_IMP_RENDER_TYPE_SPHERE = 1,
	P_IMP_RENDER_TYPE_SPRITE = 2,
	P_IMP_RENDER_TYPE_OBJECT = 10,

	// groups
	P_IMP_SETUP					= 1000,
	P_IMP_CHANNELS,
	P_IMP_DISPLAY,
	// --
	P_IMP_VECTOR,
	P_IMP_SCALAR,

	// setup
	P_IMP_FILE_PATH,
	P_IMP_NAME,
	P_IMP_PADDING,
	P_IMP_CACHE_MODE,
	P_IMP_CACHE_CORE,
	P_IMP_START_FRAME,
	P_IMP_END_FRAME,
	P_IMP_OFFSET,
	P_IMP_LOD,
	P_IMP_LIFE,
	P_IMP_LOCK_CURRENT,
	P_IMP_LOCK_LAST,
	P_IMP_INVERT_SEQUENCE,

	// channels
   // DEPRECATED old parameters (<2.4.3)
	P_IMP_VELOCITY,
	P_IMP_VELOCITY_V,
	P_IMP_FORCE,
	P_IMP_FORCE_V,
	P_IMP_VORTICITY,
	P_IMP_VORTICITY_V,
	P_IMP_NORMAL,
	P_IMP_NORMAL_V,
	P_IMP_TEXTURE,
	P_IMP_TEXTURE_V,
	P_IMP_NEIGHBOURS,
	P_IMP_NEIGHBOURS_V,
	P_IMP_INFOBIT,
	P_IMP_INFOBIT_V,
	P_IMP_AGE,
	P_IMP_AGE_V,
	P_IMP_ISOLATION,
	P_IMP_ISOLATION_V,
	P_IMP_VISCOSITY,
	P_IMP_VISCOSITY_V,
	P_IMP_DENSITY,
	P_IMP_DENSITY_V,
	P_IMP_PRESSURE,
	P_IMP_PRESSURE_V,
	P_IMP_MASS,
	P_IMP_MASS_V,
	P_IMP_TEMPERATURE,
	P_IMP_TEMPERATURE_V,
	P_IMP_ID,
	P_IMP_ID_V,

	// display
	P_IMP_DISPLAY_MODE,
	P_IMP_CIRCLES_DIR,
	P_IMP_RADIUS,
	P_IMP_COLOR_MODE,
	P_IMP_MIN_COLOR,
	P_IMP_MAX_COLOR,
	P_IMP_DISP_COLOR,

	P_IMP_USERDATA,
	P_IMP_FILE_TYPE,
	P_IMP_KEEP_ORDER,

	// v2.1.4 Maxwell - RF integration
	P_IMP_CURRENT_PATH,
	// v2.1.5 scale
	P_IMP_SCALE,
	// rendering
	P_IMP_RENDERING,
	P_IMP_GRP_RENDER,
	P_IMP_RENDER_TYPE,
	P_IMP_RENDER_OBJECT,
	P_IMP_RENDER_RADIUS,

    // v2.4.0
	P_IMP_DISPLAY_AUTO_RANGE,
	P_IMP_DISPLAY_MIN,
	P_IMP_DISPLAY_MAX,
	P_IMP_DISPLAY_CURRENT_MIN,
	P_IMP_DISPLAY_CURRENT_MAX,
   P_IMP_ADD_PARTICLE_SHADER,

   // v2.4.3
   P_IMP_BLUR_LENGTH,
   P_IMP_GRP_CHANNEL_OPERATIONS,
   P_IMP_GRP_CHOP_LIST,
   P_IMP_ENABLE_CHOPS,
   P_IMP_ADD_CHOP,
   P_IMP_NUM_CHOPS,

	P_IMP_CHAN_VELOCITY,
	P_IMP_CHAN_FORCE,
	P_IMP_CHAN_VORTICITY,
	P_IMP_CHAN_NORMAL,
	P_IMP_CHAN_TEXTURE,
	P_IMP_CHAN_NEIGHBOURS,
	P_IMP_CHAN_INFOBIT,
	P_IMP_CHAN_AGE,
	P_IMP_CHAN_ISOLATION,
	P_IMP_CHAN_VISCOSITY,
	P_IMP_CHAN_DENSITY,
	P_IMP_CHAN_PRESSURE,
	P_IMP_CHAN_MASS,
	P_IMP_CHAN_TEMPERATURE,
	P_IMP_CHAN_ID,

   P_IMP_SHARE_ASSETS,

   P_IMP_RENDER_FRAME,
   P_IMP_MB_ITERATION,
   P_IMP_LAST_RENDER_FRAME,
   
   // NOTE 10000 - 11000 range is for channel operations
   P_IMP_CHOP_CHANNEL = 10000, 
   P_IMP_CHOP_OPERATOR = 10100, 
   P_IMP_CHOP_TARGET_TYPE = 10200, 
   P_IMP_CHOP_TARGET_CHANNEL = 10300, 
   P_IMP_CHOP_TARGET_VALUE = 10400, 
   P_IMP_CHOP_UP = 10500, 
   P_IMP_CHOP_DOWN = 10600, 
   P_IMP_CHOP_REMOVE = 10700, 
};

#endif
