#ifndef _RF_Particle_Node_H_
#define _RF_Particle_Node_H_

enum
{
	// groups
	P_NODE_SETUP					= 1000,

	// setup
	P_NODE_GROUP,

	// input ports
	P_NODE_GROUP_PORT				= 8000,
	// output ports
	P_NODE_PARTICLE_PORT,
	P_NODE_POS_PORT,
	P_NODE_VEL_PORT,
	P_NODE_FORCE_PORT,
	P_NODE_VORTICITY_PORT,
	P_NODE_NORMAL_PORT,
	P_NODE_NEIGHBORS_PORT,
	P_NODE_TEXTURE_PORT,
	P_NODE_INFO_PORT,
	P_NODE_AGE_PORT,
	P_NODE_ISOLATION_PORT,
	P_NODE_VISCOSITY_PORT,
	P_NODE_DENSITY_PORT,
	P_NODE_PRESSURE_PORT,
	P_NODE_MASS_PORT,
	P_NODE_TEMPERATURE_PORT,
	P_NODE_ID_PORT,
};

#endif