#ifndef _RF_ParticleShader_H_
#define _RF_ParticleShader_H_

enum
{
    // setup
    RF_PARTICLESHADER_SETUP		= 1000,

    RF_PARTICLESHADER_USE_DISPLAY_COLOR,
	RF_PARTICLESHADER_COLOR_MODE,
	RF_PARTICLESHADER_MAG_COLOR,

	RF_PARTICLESHADER_COLOR_NONE = 0,
	RF_PARTICLESHADER_COLOR_VELOCITY = 1,
	RF_PARTICLESHADER_COLOR_NORMAL = 2,
	RF_PARTICLESHADER_COLOR_FORCE = 3,
	RF_PARTICLESHADER_COLOR_TEXTUREU = 4,
	RF_PARTICLESHADER_COLOR_TEXTUREV = 5,
	RF_PARTICLESHADER_COLOR_NEIGHBOR = 6,
	RF_PARTICLESHADER_COLOR_AGE = 7,
	RF_PARTICLESHADER_COLOR_ISOLATION = 8,
	RF_PARTICLESHADER_COLOR_VISCOSITY = 9,
	RF_PARTICLESHADER_COLOR_DENSITY = 10,
	RF_PARTICLESHADER_COLOR_PRESSURE = 11,
	RF_PARTICLESHADER_COLOR_MASS = 12,
	RF_PARTICLESHADER_COLOR_TEMPERATURE = 13,
	RF_PARTICLESHADER_COLOR_VORTICITY = 14,
    
    RF_PARTICLESHADER_INSTANCE_COLOR = 99999,
};

#endif
