CONTAINER RF_PARTICLE_IMPORTER
{
	NAME RFParticleImporter;
	INCLUDE Obase;

	GROUP P_IMP_SETUP
	{
		DEFAULT 1;
		
		FILENAME P_IMP_FILE_PATH {}
		STATICTEXT P_IMP_NAME {ANIM OFF;}
		LONG P_IMP_PADDING {MINSLIDER 0; MAXSLIDER 10;}
		LONG P_IMP_CACHE_MODE
		{
			CYCLE
			{
				P_IMP_CURRENT_FRAME;
				P_IMP_CORE_FRAME;
				P_IMP_ALL_FRAME;
			}
		}
		LONG P_IMP_CACHE_CORE {MIN 0;}
		LONG P_IMP_START_FRAME {MIN 0;}
		LONG P_IMP_END_FRAME {MIN 0;}
		LONG P_IMP_OFFSET {}
		REAL P_IMP_LOD {MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER;}
		REAL P_IMP_SCALE {MIN 0.0;}
      REAL P_IMP_BLUR_LENGTH {MIN 0.0;}
		BASETIME P_IMP_LIFE {}
		BOOL P_IMP_KEEP_ORDER {}
		BOOL P_IMP_LOCK_CURRENT {}
		BOOL P_IMP_LOCK_LAST {}
		BOOL P_IMP_INVERT_SEQUENCE {}
      SEPARATOR {LINE;}
      BOOL P_IMP_SHARE_ASSETS {}
	}

//   GROUP P_IMP_CHANNELS
//   {
//      BOOL P_IMP_CHAN_VELOCITY {}
//      BOOL P_IMP_CHAN_FORCE {}
//      BOOL P_IMP_CHAN_VORTICITY {}
//      BOOL P_IMP_CHAN_NORMAL {}
//      BOOL P_IMP_CHAN_TEXTURE {}
//      BOOL P_IMP_CHAN_NEIGHBOURS {}
//      BOOL P_IMP_CHAN_INFOBIT {}
//      BOOL P_IMP_CHAN_AGE {}
//      BOOL P_IMP_CHAN_ISOLATION {}
//      BOOL P_IMP_CHAN_VISCOSITY {}
//      BOOL P_IMP_CHAN_DENSITY {}
//      BOOL P_IMP_CHAN_PRESSURE {}
//      BOOL P_IMP_CHAN_MASS {}
//      BOOL P_IMP_CHAN_TEMPERATURE {}
//      BOOL P_IMP_CHAN_ID {}
//
//      GROUP P_IMP_GRP_CHANNEL_OPERATIONS
//      {
//         DEFAULT 1;
//
//         BOOL P_IMP_ENABLE_CHOPS {}
//         BUTTON P_IMP_ADD_CHOP {}
//         SEPARATOR {LINE;}
//         
//         GROUP P_IMP_GRP_CHOP_LIST
//         {
//            DEFAULT 1;
//            COLUMNS 7;
//
//            // content is generated dynamically
//         }
//      }
//   }
	
	GROUP P_IMP_DISPLAY
	{
		LONG P_IMP_DISPLAY_MODE
		{
			CYCLE
			{
				P_IMP_TPDEFAULT;
				P_IMP_PARTICLES;
				P_IMP_CIRCLES;
				P_IMP_BOX;
			}
		}
		LONG P_IMP_CIRCLES_DIR
		{
			CYCLE
			{
				P_IMP_CAMERA;
				P_IMP_XY;
				P_IMP_YZ;
				P_IMP_XZ;
			}
		}
		REAL P_IMP_RADIUS {MIN 0.0; STEP 0.01;}
		LONG P_IMP_COLOR_MODE
		{
			CYCLE
			{
				P_IMP_COLOR_NONE;
				P_IMP_COLOR_VELOCITY;
				P_IMP_COLOR_NORMAL;
				P_IMP_COLOR_FORCE;
				P_IMP_COLOR_TEXTUREU;
				P_IMP_COLOR_TEXTUREV;
				P_IMP_COLOR_NEIGHBOR;
				P_IMP_COLOR_AGE;
				P_IMP_COLOR_ISOLATION;
				P_IMP_COLOR_VISCOSITY;
				P_IMP_COLOR_DENSITY;
				P_IMP_COLOR_PRESSURE;
				P_IMP_COLOR_MASS;
				P_IMP_COLOR_TEMPERATURE;
				P_IMP_COLOR_VORTICITY;
			}
		}
		GRADIENT P_IMP_DISP_COLOR {COLOR;}
		BOOL P_IMP_DISPLAY_AUTO_RANGE {}
		REAL P_IMP_DISPLAY_MIN {}
		REAL P_IMP_DISPLAY_MAX {}
		REAL P_IMP_DISPLAY_CURRENT_MIN {}
		REAL P_IMP_DISPLAY_CURRENT_MAX {}
	}

	GROUP P_IMP_GRP_RENDER
	{
		LONG P_IMP_RENDER_TYPE
		{
			CYCLE
			{
				P_IMP_RENDER_TYPE_POINT;
				P_IMP_RENDER_TYPE_SPHERE;
				P_IMP_RENDER_TYPE_SPRITE;
				P_IMP_RENDER_TYPE_OBJECT;
			}
		}
		REAL P_IMP_RENDER_RADIUS {MIN 0.0; UNIT METER;}
		LINK P_IMP_RENDER_OBJECT {ACCEPT {Obase;}}
      BUTTON P_IMP_ADD_PARTICLE_SHADER {}
	}
}
