#ifndef _RF_SD_Reader_H_
#define _RF_SD_Reader_H_

enum
{
	// groups
	RF_SD_READER_SETUP				= 6000,

	RF_SD_READER_FILE,
	RF_SD_READER_START,
	RF_SD_READER_END,
	RF_SD_READER_OFFSET,
	RF_SD_READER_SCALE,
	RF_SD_READER_LOCK_LAST,
	RF_SD_READER_LOCK_CURRENT,
	RF_SD_READER_INVERT_SEQUENCE,
	RF_SD_READER_CREATEKEYS,
	RF_SD_READER_REMOVEKEYS,

	RF_SD_READER_CURRENT_FRAME,

   // v2.4.3
   RF_SD_READER_SHARE_ASSETS,
};

#endif
