CONTAINER RF_SD_READER
{
	NAME RFSDReader;
	INCLUDE Obase;

	GROUP RF_SD_READER_SETUP
	{
		DEFAULT 1;
		
		FILENAME RF_SD_READER_FILE {}
		LONG RF_SD_READER_START {}
		LONG RF_SD_READER_END {}
		LONG RF_SD_READER_OFFSET {}
		REAL RF_SD_READER_SCALE {STEP 0.1;}
		BOOL RF_SD_READER_LOCK_LAST {}
		BOOL RF_SD_READER_LOCK_CURRENT {}
		BOOL RF_SD_READER_INVERT_SEQUENCE {}
      SEPARATOR {LINE;}		
		BUTTON RF_SD_READER_CREATEKEYS {}
		BUTTON RF_SD_READER_REMOVEKEYS {}
      SEPARATOR {LINE;}
      BOOL RF_SD_READER_SHARE_ASSETS {}
	}
}

