Composition {
	CurrentTime = 26,
	RenderRange = { 0, 1000, },
	GlobalRange = { 0, 1000, },
	CurrentID = 14,
	HiQ = true,
	Version = "Fusion 7.5 build 1477",
	SavedOutputs = 0,
	HeldTools = 0,
	DisabledTools = 0,
	LockedTools = 0,
	AudioOffset = 0,
	AutoRenderRange = true,
	Resumable = true,
	OutputClips = {
	},
	Tools = {
		Loader1 = Loader {
			Clips = {
				Clip {
					ID = "Clip1",
					Filename = "C:\\Users\\michael.mussato.SCHERRERMEDIEN\\Dropbox\\development\\workspace\\PyPELyNE\\src\\tool_integration\\fusion\\fusionScripts\\tests\\Arches_E_PineTree_3k.hdr",
					FormatID = "HDRFormat",
					StartFrame = -1,
					LengthSetManually = true,
					TrimIn = 0,
					TrimOut = 0,
					ExtendFirst = 0,
					ExtendLast = 0,
					Loop = 0,
					AspectMode = 0,
					Depth = 0,
					TimeCode = 0,
					GlobalStart = 0,
					GlobalEnd = 0,
				},
			},
			CtrlWZoom = false,
			Inputs = {
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2", }, },
			},
			ViewInfo = OperatorInfo { Pos = { -395.255, 446.074, }, },
		},
		Shape3D1_1 = Shape3D {
			Inputs = {
				["SurfacePlaneInputs.ObjectID.ObjectID"] = Input { Value = 1, },
				["Transform3DOp.Translate.X"] = Input { Value = 2.13934682890785, },
				Shape = Input { Value = FuID { "SurfaceSphereInputs", }, },
				["MtlStdInputs.MaterialID"] = Input { Value = 1, },
				["SurfaceSphereInputs.ObjectID.ObjectID"] = Input { Value = 2, },
			},
			ViewInfo = OperatorInfo { Pos = { 642.187, 149.125, }, },
		},
		Shape3D1_1_1 = Shape3D {
			Inputs = {
				["SurfacePlaneInputs.ObjectID.ObjectID"] = Input { Value = 1, },
				["Transform3DOp.Translate.X"] = Input { Value = -2.14797559906475, },
				Shape = Input { Value = FuID { "SurfaceSphereInputs", }, },
				["MtlStdInputs.MaterialID"] = Input { Value = 1, },
				["SurfaceSphereInputs.ObjectID.ObjectID"] = Input { Value = 2, },
			},
			ViewInfo = OperatorInfo { Pos = { 376.451, 149.125, }, },
		},
		Merge3D2 = Merge3D {
			Inputs = {
				SceneInput1 = Input {
					SourceOp = "Shape3D1_1",
					Source = "Output",
				},
				SceneInput2 = Input {
					SourceOp = "Shape3D1_1_1",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 512.496, 149.125, }, },
		},
		FastNoise2 = FastNoise {
			Inputs = {
				Width = Input { Value = 1920, },
				Height = Input { Value = 1080, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2", }, },
				XScale = Input { Value = 200, },
				Color1Alpha = Input { Value = 1, },
				Gradient = Input {
					Value = Gradient {
						Colors = {
							[0] = { 0, 0, 0, 1, },
							[1] = { 1, 1, 1, 1, },
						},
					},
				},
			},
			ViewInfo = OperatorInfo { Pos = { -416.365, 346.156, }, },
		},
		ColorCorrector1 = ColorCorrector {
			Inputs = {
				WheelTintAngle1 = Input { Value = -0.0195715809024097, },
				WheelTintLength1 = Input { Value = 1, },
				ColorRanges = Input {
					Value = ColorCurves {
						Curves = {
							{
								Points = {
									{ 0, 1, },
									{ 0.4, 0.2, },
									{ 0.6, 0, },
									{ 1, 0, },
								},
							},
							{
								Points = {
									{ 0, 0, },
									{ 0.4, 0, },
									{ 0.6, 0.2, },
									{ 1, 1, },
								},
							},
						},
					},
				},
				HistogramIgnoreTransparent = Input { Value = 1, },
				Input = Input {
					SourceOp = "FastNoise2",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { -306.365, 346.156, }, },
		},
		Falloff1 = FalloffOperator {
			Inputs = {
				["FaceOn.Opacity"] = Input { Value = 1, },
				["Glancing.Red"] = Input { Value = 0.14, },
				["Glancing.Green"] = Input { Value = 0, },
				["Glancing.Blue"] = Input { Value = 0.00910115206555773, },
				Gradient = Input {
					Value = Gradient {
						Colors = {
							[0] = { 0, 0, 0, 1, },
							[1] = { 1, 1, 1, 1, },
						},
					},
				},
				FaceOnMaterial = Input {
					SourceOp = "ColorCorrector1",
					Source = "Output",
				},
				MaterialID = Input { Value = 2, },
			},
			ViewInfo = OperatorInfo { Pos = { 26.9547, 346.156, }, },
		},
		SphereMap1 = SphereMap {
			Inputs = {
				Image = Input {
					SourceOp = "Loader1",
					Source = "Output",
				},
				MaterialID = Input { Value = 4, },
			},
			ViewInfo = OperatorInfo { Pos = { -11.0135, 446.074, }, },
		},
		Reflect1 = MtlReflect {
			Inputs = {
				BackgroundMaterial = Input {
					SourceOp = "Falloff1",
					Source = "MaterialOutput",
				},
				["Reflection.ConstantStrength"] = Input { Value = 0.565, },
				["Reflection.GlancingStrength"] = Input { Value = 0.8, },
				["Reflection.Color.Material"] = Input {
					SourceOp = "SphereMap1",
					Source = "MaterialOutput",
				},
				["Refraction.RefractiveIndex.RGB"] = Input { Value = 1, },
				MaterialID = Input { Value = 3, },
			},
			ViewInfo = OperatorInfo { Pos = { 199.081, 346.156, }, },
		},
		Shape3D1 = Shape3D {
			Inputs = {
				Shape = Input { Value = FuID { "SurfaceSphereInputs", }, },
				MaterialInput = Input {
					SourceOp = "Reflect1",
					Source = "MaterialOutput",
				},
				["MtlStdInputs.MaterialID"] = Input { Value = 1, },
				["SurfacePlaneInputs.ObjectID.ObjectID"] = Input { Value = 1, },
				["SurfaceSphereInputs.ObjectID.ObjectID"] = Input { Value = 2, },
			},
			ViewInfo = OperatorInfo { Pos = { 362.671, 346.156, }, },
		},
		Merge3D1 = Merge3D {
			Inputs = {
				SceneInput1 = Input {
					SourceOp = "Merge3D2",
					Source = "Output",
				},
				SceneInput2 = Input {
					SourceOp = "Shape3D1",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 512.496, 346.156, }, },
		},
	},
	Views = {
		{
			FrameTypeID = "ChildFrame",
			Mode = 3,
			LayoutPreset = 0,
			Left = 50,
			Top = 50,
			Width = 1570,
			Height = 762,
			Views = ordered() {
				Main = MultiView {
					Active = "Flow",
					ViewList = ordered() {
						Flow = "FlowView",
						Console = "ConsoleView",
						Timeline = "TimelineView",
						Spline = "SplineEditorView",
						Info = "InfoView",
						Chat = "ChatView",
					},
					Flow = FlowView {
						Flags = {
							Navigator = true,
							ConnectedSnap = true,
							PipesAlways = true,
							ShowGrid = false,
							AutoSnap = true,
							RemoveRouters = true,
						},
						NavigatorSize = { 100, 100, },
						Direction = "Vertical",
						PipeStyle = "Direct",
						Scale = 1.50525,
						Offset = { 586.196, -260.372, },
					},
					Timeline = TimelineView {
						TreeControlState = {
						},
						DisplayMode = "All Tools",
						ShowCurrentTimeTools = false,
						Filter = "Show All",
						ShowSelectedTools = false,
						ShowAnimatedToolsOnly = false,
						ShowEditBoxes = false,
						KeyFrameView = {
							Position = { Left = 130, Bottom = 511, },
							ScaleX = 0.75187969924812,
							OffsetX = -49.624060150376,
							OffsetY = 0,
							AutoScaling = "scroll",
							AutoSnapTo = "frame",
							AutoSnapToGuidelines = false,
							GuidelinesGrabEnabled = true,
							GuidelinesSnapTo = "none",
						},
						Spreadsheet = { LeftPos = 130, Visible = false, },
					},
					Spline = SplineEditorView {
						LeftPos = 206,
						ScaleX = 0.2,
						ScaleY = 0.00343642611683849,
						OffsetX = -3.59999999999999,
						OffsetY = 0,
						AutoScaling = "scroll",
						AutoSnapTo = "frame",
						AutoSnapToGuidelines = true,
						GuidelinesSnapTo = "frame",
						ShowKeyMarkers = false,
						IndependentHandles = false,
						ShowNonSplineModifiers = false,
						GuidelinesGrabEnabled = true,
						ShowOneToolOnly = false,
						ShowSelectedTools = false,
						ShowAllInputs = false,
						Filter = "Show All",
					},
				},
				Controls = MultiView {
					Active = "Tools",
					ViewList = ordered() {
						Tools = "ControlView",
						Modifiers = "ModifierView",
					},
				},
				Left = "PreviewContainer",
				Right = "PreviewContainer",
				Transport = "TransportView",
				Time = "TimeView",
			},
			Layout = {
				Columns = 2,
				RatioX = 1,
				RatioY = 1,
				{
					Rows = 3,
					RatioX = 0.79406068431246,
					RatioY = 100,
					{
						Columns = 2,
						RatioX = 1,
						RatioY = 0.462290502793296,
						{ ID = "Left", RatioX = 0.50040749796251, RatioY = 100, Pop = true, },
						{ ID = "Right", RatioX = 0.49959250203749, Pop = true, },
						Pop = true,
					},
					{ ID = "Main", RatioY = 0.462290502793296, Pop = true, },
					{ ID = "Time", SnapY = 52, Flat = true, },
				},
				{
					Rows = 2,
					PixelX = 317,
					{ ID = "Controls", RatioX = 1, RatioY = 1, },
					{ ID = "Transport", FixedY = -2, },
				},
			},
		},
	},
	Prefs = {
		Comp = {
			Paths = {
			},
			FlowView = {
				ShowNavigator = 1,
				PipesOnTop = true,
				ConnectedSnap = true,
				ShowGrid = false,
				Direction = 1,
			},
			LastFile = "\\\\SMSRV-001\\Allgemein\\Kunden\\UBS\\UBS_Artcontent_2014\\tasks\\0022__background\\background\\output\\TEX_images\\ArtContent_BG.jpg",
			FrameFormat = {
				GuideRatio = 1.77777777777778,
				PerFeet = 1,
				Rate = 25,
				Width = 1920,
				Height = 1080,
				Name = "HDTV 1080",
			},
			SplineEditor = {
				AutoSnap = {
					Keys = 18,
				},
			},
			Views = {
				Defaults = {
					CtrlWheelZoom = false,
				},
				View1 = {
					PrevCtrlInactiveColor = 0,
					PickW = 0,
					PickH = 0,
					PrevCtrlActiveColor = 0,
					Viewer = {
						LUTPlugin = "As...",
					},
					SideB = {
						PrevCtrlInactiveColor = 65280,
						PickW = 1,
						PickH = 1,
						PrevCtrlActiveColor = 255,
						Viewer = {
							EnableLUTs = false,
							LUTPlugin = "HDTV 1080",
							NearZ = 0,
							FitMarginX = 0,
							FitMarginType = 0,
							FarZ = -1000,
							FitMarginY = 0,
						},
					},
				},
				Right = {
					SideB = {
						PrevCtrlInactiveColor = 65280,
						PickW = 1,
						PickH = 1,
						PrevCtrlActiveColor = 255,
						Viewer = {
							EnableLUTs = false,
							LUTPlugin = "",
							NearZ = 0,
							FitMarginX = 0,
							FitMarginType = 0,
							FarZ = -1000,
							FitMarginY = 0,
						},
					},
					Viewer = {
					},
				},
				Left = {
					SideB = {
						PrevCtrlInactiveColor = 65280,
						PickW = 1,
						PickH = 1,
						PrevCtrlActiveColor = 255,
						Viewer = {
							EnableLUTs = false,
							LUTPlugin = "Center",
							NearZ = 0,
							FitMarginX = 0,
							FitMarginType = 0,
							FarZ = -1000,
							FitMarginY = 0,
						},
					},
					Viewer = {
						LUTPlugin = "7.5",
					},
					View3D = {
						CameraName = "Perspective",
						CamPersp = {
							Position = {
								X = -0.103478014469147,
								Y = 0.0877119898796082,
								Z = -0.0659316405653954,
							},
							Rotation = {
								X = 8.40000057220459,
								Y = -0.800000488758087,
								Z = 0,
							},
							Scale = 0.664342939853668,
						},
						CamFront = {
							Position = {
								X = 0,
								Y = 0,
								Z = 0,
							},
							Rotation = {
								X = 0,
								Y = 0,
								Z = 0,
							},
							Scale = 1,
						},
						CamTop = {
							Position = {
								X = 0,
								Y = 0,
								Z = 0,
							},
							Rotation = {
								X = 90,
								Y = 0,
								Z = 0,
							},
							Scale = 1,
						},
						CamRight = {
							Position = {
								X = 0,
								Y = 0,
								Z = 0,
							},
							Rotation = {
								X = 0,
								Y = -90,
								Z = 0,
							},
							Scale = 1,
						},
						CamLeft = {
							Position = {
								X = 0,
								Y = 0,
								Z = 0,
							},
							Rotation = {
								X = 0,
								Y = 90,
								Z = 0,
							},
							Scale = 1,
						},
						Options = {
							Lighting = true,
						},
					},
					MaterialViewer = {
						Camera = {
							Rotation = {
								X = 24.1999988555908,
								Y = 297.399993896484,
								Z = 0,
							},
						},
					},
				},
			},
			Memory = {
				Render = {
					SimultaneousBranching = true,
				},
				FramesAtOnce = 5,
				Interactive = {
					SimultaneousBranching = true,
				},
			},
			QuickTime = {
			},
		},
	},
}

 