// C4D-DialogResource

DIALOG RF_MESH_EXPORTER
{
  NAME RFMeshExporter;
  
  GROUP M_EXP_SETUP
  {
	NAME M_EXP_SETUP;
	FIT_H; FIT_V; SCALE_V; SCALE_H;
	COLUMNS 1;
	
	GROUP
	{
		COLUMNS 2;
	
		STATICTEXT {NAME M_EXP_OBJ; SIZE -100,-15;}
		COMBOBOX M_EXP_OBJ
		{
			CHILDS 
			{
				// comes from the code
			}
		}

		STATICTEXT {NAME M_EXP_DIR;}
		FILENAME M_EXP_DIR {DIRECTORY; SIZE -250,-10;}

		STATICTEXT {NAME M_EXP_NAME;}
		EDITTEXT M_EXP_NAME {}
			
		STATICTEXT {NAME M_EXP_PADDING;}
		EDITSLIDER M_EXP_PADDING {}
	}
	GROUP
	{
		COLUMNS 2;
		
		STATICTEXT {NAME M_EXP_START; SIZE -100,-12;}
  		EDITNUMBERARROWS M_EXP_START {}

		STATICTEXT {NAME M_EXP_END;}
		EDITNUMBERARROWS M_EXP_END {}

		STATICTEXT {NAME M_EXP_INC;}
		EDITNUMBERARROWS M_EXP_INC {}
	}
	GROUP
	{
		COLUMNS 2;
			
		STATICTEXT {NAME M_EXP_TEX; SIZE -100,-12;}
		CHECKBOX M_EXP_TEX {}

		//STATICTEXT {NAME M_EXP_NUMF; SIZE -100,-12;}
		//EDITNUMBERARROWS M_EXP_NUMF {}

		STATICTEXT {NAME M_EXP_VEL; SIZE -100,-12;}
		CHECKBOX M_EXP_VEL {}

		STATICTEXT {NAME M_EXP_RECALC_VEL; SIZE -100,-12;}
		CHECKBOX M_EXP_RECALC_VEL {}
	}
		
	STATICTEXT M_EXP_INFO {};
		
	GROUP 
	{  
		CENTER_H;
		COLUMNS 2;
			
		BUTTON M_EXP_BUTTON {NAME M_EXP_BUTTON;}
		BUTTON M_EXP_CANCEL {NAME M_EXP_CANCEL;}
	}
  }
}
