// C4D-DialogResource

DIALOG RF_PARTICLE_EXPORTER
{
  NAME RFParticleExporter;
  
  TAB P_EXP_TAB 
  {
	  GROUP P_EXP_SETUP
	  {
		NAME P_EXP_SETUP;
		COLUMNS 1;
		
		GROUP
		{
			COLUMNS 2;
		
			STATICTEXT {NAME P_EXP_PSYS; SIZE -75,-15;}
			COMBOBOX P_EXP_PSYS
			{
				CHILDS 
				{
					// comes from the code
				}
			}

			STATICTEXT {NAME P_EXP_FORMAT;}
			COMBOBOX P_EXP_FORMAT 
            {
    			CHILDS
	    		{
		    		P_EXP_FORMAT_RF2012, P_EXP_FORMAT_RF2012_STR;
		    		P_EXP_FORMAT_RF2013, P_EXP_FORMAT_RF2013_STR;
    			}
            }

			STATICTEXT {NAME P_EXP_DIR;}
			FILENAME P_EXP_DIR {DIRECTORY; SIZE -200,-10;}

			STATICTEXT {NAME P_EXP_NAME;}
			EDITTEXT P_EXP_NAME {}
			
			STATICTEXT {NAME P_EXP_PADDING;}
			EDITSLIDER P_EXP_PADDING {}
		}
		GROUP
		{
			COLUMNS 2;
			
			STATICTEXT {NAME P_EXP_START; SIZE -75,-12;}
  			EDITNUMBERARROWS P_EXP_START {}

			STATICTEXT {NAME P_EXP_END;}
  			EDITNUMBERARROWS P_EXP_END {}

			STATICTEXT {NAME P_EXP_INC;}
  			EDITNUMBERARROWS P_EXP_INC {}
		}
		
		STATICTEXT P_EXP_INFO {};
		
	    GROUP 
		{  
		    CENTER_H;
			COLUMNS 2;
			
			BUTTON P_EXP_BUTTON {NAME P_EXP_BUTTON;}
			BUTTON P_EXP_CANCEL {NAME P_EXP_CANCEL;}
		}
	}
	  	
	GROUP P_EXP_PARTICLE
	{
		NAME P_EXP_PARTICLE;
		COLUMNS 1;
		
		GROUP
		{
			COLUMNS 2;
			
			STATICTEXT {NAME P_EXP_FLUIDNAME; SIZE -90, -10;}
  			EDITTEXT P_EXP_FLUIDNAME {SIZE -120,-10;}

			STATICTEXT {NAME P_EXP_FLUIDTYPE;}
  			COMBOBOX P_EXP_FLUIDTYPE 
  			{
  				CHILDS 
  				{
  					P_EXP_GAS, P_EXP_GAS;
  					P_EXP_LIQUID, P_EXP_LIQUID;
  					P_EXP_DUMB, P_EXP_DUMB;
  					P_EXP_ELASTIC, P_EXP_ELASTIC;
  				}
  			}

			STATICTEXT {NAME P_EXP_FPS;}
  			COMBOBOX P_EXP_FPS
  			{
  				CHILDS 
  				{
  					P_EXP_FPS30, P_EXP_FPS30;
  					P_EXP_FPS25, P_EXP_FPS25;
  					P_EXP_FPS24, P_EXP_FPS24;
  				}
  			}
  		}
		GROUP
		{
			COLUMNS 2;
			
			STATICTEXT {NAME P_EXP_SCENE_SCALE; SIZE -90,-10;}
			EDITNUMBER P_EXP_SCENE_SCALE {SIZE -45,-10;}

			STATICTEXT {NAME P_EXP_RADIUS;}
			EDITNUMBER P_EXP_RADIUS {}

			STATICTEXT {NAME P_EXP_EMITTER_POSX;}
			EDITNUMBER P_EXP_EMITTER_POSX {}
			STATICTEXT {NAME P_EXP_EMITTER_POSY;}
			EDITNUMBER P_EXP_EMITTER_POSY {}
			STATICTEXT {NAME P_EXP_EMITTER_POSZ;}
			EDITNUMBER P_EXP_EMITTER_POSZ {}

			STATICTEXT {NAME P_EXP_EMITTER_ROTX;}
			EDITNUMBER P_EXP_EMITTER_ROTX {}
			STATICTEXT {NAME P_EXP_EMITTER_ROTY;}
			EDITNUMBER P_EXP_EMITTER_ROTY {}
			STATICTEXT {NAME P_EXP_EMITTER_ROTZ;}
			EDITNUMBER P_EXP_EMITTER_ROTZ {}

			STATICTEXT {NAME P_EXP_EMITTER_SCALEX;}
			EDITNUMBER P_EXP_EMITTER_SCALEX {}
			STATICTEXT {NAME P_EXP_EMITTER_SCALEY;}
			EDITNUMBER P_EXP_EMITTER_SCALEY {}
			STATICTEXT {NAME P_EXP_EMITTER_SCALEZ;}
			EDITNUMBER P_EXP_EMITTER_SCALEZ {}

			STATICTEXT {NAME P_EXP_CALC_VELOCITY;}
			CHECKBOX P_EXP_CALC_VELOCITY {}
		}
	}
  }
}
