// C4D-DialogResource

DIALOG RF_SD_IMPORTER
{
  NAME RFSDImporter;
  
  GROUP SD_IMP_SETUP
  {
	NAME SD_IMP_SETUP;
	COLUMNS 2;
	
	STATICTEXT {NAME SD_IMP_CAM;}
	FILENAME SD_IMP_CAM {SIZE 500,10;}

	STATICTEXT {NAME SD_IMP_OBJ;}
	FILENAME SD_IMP_OBJ {SIZE 500,10;}

	STATICTEXT SD_IMP_OBJNUM {NAME SD_IMP_OBJNUM;}
	STATICTEXT SD_IMP_OBJDESC {NAME SD_IMP_OBJDESC;}
	
//	STATICTEXT {NAME SD_IMP_SCALE;}
//	EDITNUMBERARROWS SD_IMP_SCALE {}

	STATICTEXT {}
	CHECKBOX SD_IMP_CREATE {NAME SD_IMP_CREATE;}

	STATICTEXT {}
	CHECKBOX SD_IMP_TEX {NAME SD_IMP_TEX;}

	STATICTEXT {}
	CHECKBOX SD_IMP_NORM {NAME SD_IMP_NORM;}  	

	STATICTEXT {}
	CHECKBOX SD_IMP_KEYS {NAME SD_IMP_KEYS;}  	
  }  

  GROUP 
  {  
	CENTER_H;
	COLUMNS 2;
	
	BUTTON SD_IMP_BUTTON {NAME SD_IMP_BUTTON;}
	BUTTON SD_IMP_CANCEL {NAME SD_IMP_CANCEL;}
  }
}
