CONTAINER ToolPointCollapse
{
	NAME ToolPointCollapse;
	INCLUDE ToolBase;

	GROUP MDATA_MAINGROUP
	{
		BOOL PCOLL_ONLY_VISIBLE {}
		LONG PCOLL_SEARCH_RADIUS { MIN 0; MINEX; MAX 1000; STEP 10; CUSTOMGUI LONGSLIDER; }
	}
	
	HIDE MDATA_COMMANDGROUP;
}
