CONTAINER VPpointposition
{
	NAME VPpointposition;
	INCLUDE VPbase;

	GROUP ID_VIDEOPOSTPROPERTIES
	{
		BOOL VP_POINTPOSITION_INVERTX { }
		BOOL VP_POINTPOSITION_INVERTY { }
		BOOL VP_POINTPOSITION_INVERTZ { }
	}
}
